packages:
  - apps/*
  - apps/indexers/*

allowBuilds:
  '@cosmology/protobufjs': true
  '@scarf/scarf': true
  bufferutil: true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  keccak: true
  protobufjs: true
  secp256k1: true
  sharp: true
  tiny-secp256k1: true
  utf-8-validate: true
  workerd: true
